export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD'
export const GET_FRIENDS_PENDING = 'GET_FRIENDS_PENDING'
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS'
export const GET_FRIENDS_FAILED = 'GET_FRIENDS_FAILED'